name: Release management

on:
  release:
    types: [released, prereleased]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: apexskier/github-release-commenter@v1
        with:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}
